- name: Cài đặt và cấu hình Nginx trên Target Environment
  hosts: all
  become: yes      
  
  tasks:
    - name: Cập nhật apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Cài đặt package Nginx
      apt:
        name: nginx
        state: present

    - name: Đảm bảo dịch vụ Nginx đang chạy và tự khởi động cùng hệ thống
      service:
        name: nginx
        state: started
        enabled: yes
